/* CLASSDEF.H
*  ==========
*
*  PROGRAM DECSRIPTION
*  ===================
*
*
*  PROGRAM INFORMATION
*  ===================
*  Author   : M G Davidson
*  Date     : 01/11/1994
*  Version  : 2.0
*  Language : C++ (BORLAND v3.1)
*
*/

/* Header file for Class definitions */

#define WIN31
#define STRICT
#define NOTOOLBUTTONS  1
#define NOSELECTORS    17
#define INIFILENAME    "RAILC.INI"
#define HELPFILENAME   "RAILC.HLP"
#define APPNAME        "Rail Control"

#include <checkbox.h>
#include <commdlg.h>
#include <owl.h>
#include <math.h>
#include <mmsystem.h>
#include <owlrc.h>
#include <radiobut.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <strstream.h>
#include <time.h>
#include <window.h>
#include "ctl3d.h"
#include "section.h"
#include "platdata.h"
#include "routes.h"
#include "locos.h"
#include "timetabl.h"
#include "general.h"
#include "toolbutt.h"
#include "toolbar.h"
#include "statbar.h"
#include "selector.h"
#include "arrivals.h"
#include "departur.h"
#include "platform.h"
#include "locoyard.h"
#include "configur.h"
#include "layout.h"
#include "railc.h"
#include "finish.h"
#include "start.h"
#include "startup.h"
#include "about.h"


